Adding CodeCell ESP32C3 new 3rd part board
espressif/arduino-esp32 pull request #10177
Opened 2024-08-16 07:52 UTC by microbotsio

Adding CodeCell ESP32C3 new 3rd part board with updating boards.txt and adding the pins_arduino.h in the variant/CodeCell folder.

2024-08-16 08:30 UTC, P-R-O-C-H-Y requested changes
@microbotsio PTAL

2024-08-16 08:30 UTC, P-R-O-C-H-Y commented on variants/CodeCell/pins_arduino.h
> +
One small change, this needs to be removed as its defined globally :)
```suggestion
```

2024-08-16 08:37 UTC, P-R-O-C-H-Y approved these changes
LGTM

2024-08-16 08:43 UTC, microbotsio commented
Can you explain why it the boards test and failed to merge?

2024-08-16 08:45 UTC, P-R-O-C-H-Y requested changes
@microbotsio

2024-08-16 08:45 UTC, P-R-O-C-H-Y commented on boards.txt
> +codecell.build.variant=codecell
The variant name is not matching the variant folder. Please change the variant folder to lowercase.

2024-08-16 09:41 UTC, P-R-O-C-H-Y approved these changes
LGTM

2024-08-16 09:47 UTC, microbotsio commented
Is there anything else we need to do from our side?

2024-08-16 09:49 UTC, P-R-O-C-H-Y commented
> Is there anything else we need to do from our side?

@microbotsio All good from your side, the PR ready to be merged (marked as pending merge). We will merge it soon :)

2024-08-16 09:50 UTC, microbotsio commented
great thanks!

2024-08-16 13:40 UTC, merged

2024-08-27 09:47 UTC, microbotsio commented
Could you please let me know when the next 3.0.5 release is scheduled? :) 

We like our board to show up in Board Manager

2025-01-16 04:10 UTC, guswynn commented
@microbotsio why was SCK mapped to pin 4, when that seems to be used for something else (referencing https://github.com/microbotsio/CodeCell/blob/main/hardware/CodeCell%20Schematics.png)? My understanding is that the ESP32 can make peripherals at will, so this can be overridden when constructing the `SPIClass`, but if I am reading https://www.espressif.com/sites/default/files/documentation/esp32-c3_datasheet_en.pdf#cd-pins-io-mux-gpio, correctly, the high throughput using the IO MUX would be:

```
static const uint8_t SS = 5; // this one would need to go through the gpio mux, so it will have a latency hit; the direct pin is 10, as far as i can tell, which is used for something else. It's unclear if this affects the throughput of the spi interface in general.
static const uint8_t MOSI = 2;
static const uint8_t MISO = 7;
static const uint8_t SCK = 6;
```

2025-01-17 17:36 UTC, microbotsio commented
Thanks for taking interest in this matter! We're checking if we can
update this in the coming future


On Thu, 16 Jan 2025 at 05:10, Gus Wynn ***@***.***> wrote:

> @microbotsio <https://github.com/microbotsio> why was SCK mapped to pin
> 4, when that seems to be used for something else (referencing
> https://github.com/microbotsio/CodeCell/blob/main/hardware/CodeCell%20Schematics.png)?
> My understanding is that the ESP32 can make peripherals at will, so this
> can be overridden when constructing the SPIClass, but if I am reading
> https://www.espressif.com/sites/default/files/documentation/esp32-c3_datasheet_en.pdf#cd-pins-io-mux-gpio,
> correctly, the high throughput using the IO MUX would be:
>
> static const uint8_t SS = 5; // this one would need to go through the gpio mux, so it will have a latency hit; the direct pin is 10, as far as i can tell, which is used for something else. It's unclear if this affects the throughput of the spi interface in general.
> static const uint8_t MOSI = 2;
> static const uint8_t MISO = 7;
> static const uint8_t SCK = 6;
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/espressif/arduino-esp32/pull/10177#issuecomment-2594437869>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BIOADCTKNJF6RJYR3B4X74D2K4WL3AVCNFSM6AAAAABMTSVJ52VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKOJUGQZTOOBWHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>