feat(esp32): Add Arduino libraries for Lora 4G Module and Node Wifi o…
espressif/arduino-esp32 pull request #10402
Opened 2024-10-02 13:32 UTC by Bharat-Pi

…f BharatPi boards variant.

## Description of Change
This Pull Request add support to three new hardware on the market using ESP32 modules, Bharat Pi Node Wifi , Bharat Pi A7672s 4G and Bharat Pi LoRa modules. Links to the hardware is provided below

Bharat Pi Node Wifi
https://bharatpi.net/product/bharat-pi-node-wifi/

Bharat Pi A7672s 4G Board
https://bharatpi.net/product/bharat-pi-4g-lte-module-with-esp32-simcom-a7672-with-gps/

Bharat Pi LoRa boards with Indian Frequency
https://bharatpi.net/product/bharat-pi-lora-module-with-esp32-lora868mhz-transreceiver-with-esp32-arduino-compatible/

These boards are used by Students, Tinkerers across 100s of different colleges and universities and we are connected with the Espressif to launch these boards.

## Tests scenarios
We have tested these changes on a Bharat Pi boards using the Arduino IDE and the ESP32 core with 4MB, 8MB and 16MB flash versions of ESP32.
We have verified that the defined pins correspond to the correct hardware pins on the board.
We tested the samples codes and libraries of our code and example codes.
You can see our test codes in this page
https://github.com/Bharat-Pi/iot-projects

## Related links
This is a support package for new variant
https://github.com/Bharat-Pi/iot-projects
https://bharatpi.net/product/bharat-pi-node-wifi/
https://bharatpi.net/product/bharat-pi-4g-lte-module-with-esp32-simcom-a7672-with-gps/
https://bharatpi.net/product/bharat-pi-lora-module-with-esp32-lora868mhz-transreceiver-with-esp32-arduino-compatible/

2024-10-02 14:15 UTC, P-R-O-C-H-Y requested changes

2024-10-02 14:15 UTC, P-R-O-C-H-Y commented on variants/BharatPi-Node-Wifi/pins_arduino.h
> +#endif /* Pins_Arduino_h */
This part is doubled, please remote it.
```suggestion
#endif /* Pins_Arduino_h */
```

2024-10-02 14:15 UTC, P-R-O-C-H-Y commented on variants/BharatPi-A7672S-4G/pins_arduino.h
> +
You are missing default SPI and I2C pins, please add them.
This must be done for all boards.
If you don't want to specify the default pin, you can use -1 as the pin so defaults from the core will be used.

2024-10-04 09:21 UTC, P-R-O-C-H-Y requested changes
@Bharat-Pi PTAL on my comments.
As you are using 4MB Flash chip, please remove other options and unusable partitions for all the boards. Thanks, otherwise its looking good.

2024-10-04 09:21 UTC, P-R-O-C-H-Y commented on boards.txt
> +BharatPi-Node-Wifi.build.board=ESP32_WROOM_DA
Please change this to proper name.
```suggestion
BharatPi-Node-Wifi.build.board=BHARATPI_NODE_WIFI
```

2024-10-04 09:21 UTC, P-R-O-C-H-Y commented on boards.txt
> +BharatPi-Node-Wifi.menu.FlashSize.16M.build.flash_size=16MB
You can remove those as the board is made with 4MB flash chip
```suggestion
```

2024-10-04 09:21 UTC, P-R-O-C-H-Y commented on boards.txt
> +BharatPi-Node-Wifi.menu.PartitionScheme.default=Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS)
Also go through all partition schemes and remove those that are not for 4MB Flash size.

2024-10-04 09:21 UTC, P-R-O-C-H-Y commented on boards.txt
> +BharatPi-A7672S-4G.build.board=ESP32_WROOM_DA
Same here:
```suggestion
BharatPi-A7672S-4G.build.board=BHARATPI_A7672S_4G
```

2024-10-04 09:21 UTC, P-R-O-C-H-Y commented on boards.txt
> +BharatPi-A7672S-4G.menu.FlashSize.16M.build.flash_size=16MB
Same here:
```suggestion
```

2024-10-04 09:21 UTC, P-R-O-C-H-Y commented on boards.txt
> +BharatPi-LoRa.build.board=ESP32_WROOM_DA
Same here:
```suggestion
BharatPi-LoRa.build.board=BHARATPI_LORA
```

2024-10-04 09:21 UTC, P-R-O-C-H-Y commented on boards.txt
> +BharatPi-LoRa.menu.FlashSize.16M.build.flash_size=16MB
If it also uses 4MB flash please remove those options and remove the unusable partitions.

2024-10-07 07:11 UTC, VojtechBartoska commented
Hello @Bharat-Pi, please take a look on proposed changes by @P-R-O-C-H-Y.

2024-10-07 08:06 UTC, Bharat-Pi commented
> Hello @Bharat-Pi, please take a look on proposed changes by @P-R-O-C-H-Y.

Somehow my comments are not shown 
Here is the comments I mentioned 

Though the board picture you see in the website has 4MB flash, We have boards with 8MB and 16MB Flash versions, which are used by ones who wants more flash memory and trying edge ai workloads. I have also mentioned the same in the description.

This is same for all three boards, Hence we would need partition and flash size of 8MB and 16MB also. 

It is showing as pending for me not sure why . I have resolved other comments regarding board name , please check and approve the PR
![image](https://github.com/user-attachments/assets/dc9a14ba-1749-4dcb-8652-ad954340170e)

2024-10-07 08:06 UTC, P-R-O-C-H-Y requested changes
@Bharat-Pi PTAL

2024-10-07 08:06 UTC, P-R-O-C-H-Y commented on boards.txt
> +BharatPi-Node-Wifi.menu.FlashSize.16M.build.flash_size=16MB
Please remove this as it's not possible option for your boards. Apply to all of them.
```suggestion
```

2024-10-07 08:06 UTC, P-R-O-C-H-Y commented on boards.txt
> +BharatPi-Node-Wifi.menu.PartitionScheme.app3M_fat9M_16MB.upload.maximum_size=3145728
Also remove those partitions -> needs 16MB of Flash. Apply to all boards please.
```suggestion
```

2024-10-07 08:09 UTC, P-R-O-C-H-Y commented on boards.txt
> +BharatPi-A7672S-4G.build.board=BHARATPI_A7672s_4G
The build.board must be uppercase, you missed the "s". Please fix it.
```suggestion
BharatPi-A7672S-4G.build.board=BHARATPI_A7672S_4G
```

2024-10-07 08:10 UTC, P-R-O-C-H-Y commented
@Bharat-Pi Thanks for the info, one small nitpick about the build.board name. Else it's looking good. Once fixed and CI passes we can merge :)

2024-10-07 08:26 UTC, Bharat-Pi commented
> @Bharat-Pi Thanks for the info, one small nitpick about the build.board name. Else it's looking good. Once fixed and CI passes we can merge :)

Fixed and pushed the changes, Thanks for the quick support. Hope it gets merged today

2024-10-07 08:40 UTC, P-R-O-C-H-Y approved these changes

2024-10-07 10:43 UTC, merged