add waveshare touch lcd
espressif/arduino-esp32 pull request #10434
Opened 2024-10-08 11:59 UTC by H-sw123

## Description of Change
Adding variant for Waveshare ESP32-S3-Touch-LCD-4 & ESP32-S3-Touch-LCD-4.3 & ESP32-S3-Touch-LCD-4.3B & ESP32-S3-Touch-LCD-5 & ESP32-S3-Touch-LCD-5B ESP32-S3-Touch-LCD-7 board

## Tests scenarios
Untested, pin definition is based on information in Waveshare wiki.

## Related links
Wiki for [ESP32-S3-Touch-LCD-4](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4)
Wiki for [ESP32-S3-Touch-LCD-4.3](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4.3)
Wiki for [ESP32-S3-Touch-LCD-4.3B](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4.3B)
Wiki for [ESP32-S3-Touch-LCD-5](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-5)
Wiki for [ESP32-S3-Touch-LCD-5B](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-5)
Wiki for [ESP32-S3-Touch-LCD-7](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-7)

2024-10-08 11:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=10434) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=10434) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=10434) it.</sub>

2024-10-11 12:15 UTC, P-R-O-C-H-Y requested changes
Hi @H-sw123, as the board comes with the 8MB flash size, please remove all 16MB partition schemes located in each board (fatflash, app3M_fat9M). Thanks

2024-10-12 02:49 UTC, H-sw123 commented
Hi, @P-R-O-C-H-Y I am a staff of waveshare. We plan to add a 16M module to our 8M product. I have added a statement in boards.txt that the flash can be selected as 8M or 16M.
![image](https://github.com/user-attachments/assets/14c61436-d05c-4cdb-ba08-aa671eef91b0)
![image](https://github.com/user-attachments/assets/298f32c0-d5b2-49f1-a217-391870fa530b)
Please keep the 16M partition.Thanks

2024-10-16 12:38 UTC, P-R-O-C-H-Y approved these changes

2024-10-16 23:39 UTC, merged