fix(zigbee): Add connected(), minor fixes, example update
espressif/arduino-esp32 pull request #10636
Opened 2024-11-22 14:21 UTC by P-R-O-C-H-Y

## Description of Change
This PR adds Zigbee.conneted() function and the Zigbee.begin() is now blocking until the Zigbee is started.
Some minor API changes + example updates.

## Tests scenarios

## Related links

2024-11-22 17:14 UTC, me-no-dev approved these changes

2024-11-22 21:31 UTC, lucasssvaz approved these changes

2024-11-24 03:17 UTC, SuGlider requested changes
LGTM.  @P-R-O-C-H-Y - Please take a look to the suggested changes.

Windows requires '\r' + '\n' at the end of a line in order to make it work with most Serial Termnals, such as PuTTY and others.

Adding '\r' doesn't affect Linux or MacOS, but is important to Windows.

2024-11-24 03:17 UTC, SuGlider commented on libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino
> +  Serial.printf("Reported temperature: %.2f°C, Humidity: %.2f%%\n", temperature, humidity);
```suggestion
  Serial.printf("Reported temperature: %.2f°C, Humidity: %.2f%%\r\n", temperature, humidity);
```

2024-11-24 03:17 UTC, SuGlider commented on libraries/Zigbee/examples/Zigbee_Temperature_Sensor/Zigbee_Temperature_Sensor.ino
> +    Serial.printf("Updated temperature sensor value to %.2f°C\n", tsens_value);
```suggestion
    Serial.printf("Updated temperature sensor value to %.2f°C\r\n", tsens_value);
```

2024-11-25 11:13 UTC, merged