feat(esp32): Added a new device(xiao esp32s3 plus)
espressif/arduino-esp32 pull request #10768
Opened 2024-12-21 05:58 UTC by is-qian

## Description of Change
feat(esp32): Added a new device from Seeed: Xiao ESP32S3 Plus

2024-12-21 05:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=10768) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=10768) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=10768) it.</sub>

2025-01-06 06:50 UTC, P-R-O-C-H-Y requested changes

2025-01-06 06:50 UTC, P-R-O-C-H-Y commented on boards.txt
> +XIAO_ESP32S3.build.flash_freq=80m
The name is wrong here. 
```suggestion
XIAO_ESP32S3_PLUS.build.flash_freq=80m
```

2025-01-17 10:41 UTC, P-R-O-C-H-Y commented on boards.txt
> +XIAO_ESP32S3_PLUS.menu.PartitionScheme.tinyuf2.build.custom_partitions=partitions-8MB-tinyuf2
The partition name does not match with the partition file name you added to the variant folder.
`partitions-8MB-tinyuf2` vs `partitions-8MB`. Please fix the naming

2025-01-20 08:39 UTC, P-R-O-C-H-Y requested changes
@is-qian Probably last error that I did not see before, is the variant folder name vs the variant name in boards.txt. You need to fix this:
Variant folder name: **XIAO_ESP32S3_Plus**
In Boards.txt XIAO_ESP32S3_PLUS.build.variant=**XIAO_ESP32S3_PLUS**

The name must be the same and its case sensitive.

2025-01-21 01:37 UTC, is-qian commented
> @is-qian Probably last error that I did not see before, is the variant folder name vs the variant name in boards.txt. You need to fix this: Variant folder name: **XIAO_ESP32S3_Plus** In Boards.txt XIAO_ESP32S3_PLUS.build.variant=**XIAO_ESP32S3_PLUS**
> 
> The name must be the same and its case sensitive.

Thank you for the reminder, I have fixed this issue.

2025-01-21 06:49 UTC, P-R-O-C-H-Y approved these changes
LGTM

2025-01-21 11:24 UTC, merged