Include nvs_commit() on three methods
espressif/arduino-esp32 pull request #5309
Opened 2021-06-19 16:53 UTC by beamholder

In response to Issue #4972 

In [Preferences.cpp](https://github.com/espressif/arduino-esp32/blob/master/libraries/Preferences/src/Preferences.cpp),  the functions:
```
Preferences::clear()
Preferences::remove()
Preferences::end()
```
should be revised to include a call to 
`nvs_commit()`
as required per 
[Non-volatile storage library](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/nvs_flash.html)
when using 
```
nvs_erase_all()
nvs_erase_key()
nvs_close()
```

2021-06-19 16:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=5309) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=5309) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=5309) it.</sub>

2021-07-02 06:26 UTC, igrr requested changes
Thanks for the PR @beamholder, it is useful! Some minor requests below...

2021-07-02 06:26 UTC, igrr commented on libraries/Preferences/src/Preferences.cpp
> +void Preferences::end(){                                         // modified to add an nvs_commit()
The comment isn't necessary, as the file change history is visible in `git log` or `git blame`, and any commit that has modified a file can be found and reverted if needed. The comments describing the changes (`// added by XXX 06/2021`) only distract from the purpose of the code.

2021-07-02 06:26 UTC, igrr commented on libraries/Preferences/src/Preferences.cpp
> +    // return true;                                         // to undo changes: uncomment this line and...
ditto, and please remove this commented out line

2021-07-02 06:26 UTC, igrr commented on libraries/Preferences/src/Preferences.cpp
> +    esp_err_t err = nvs_commit(_handle);                         // to undo changes: delete the lines from here...
Since every other method which does some modifications already calls nvs_commit, is this call actually necessary?

2021-07-02 06:26 UTC, igrr commented on libraries/Preferences/src/Preferences.cpp
> +bool Preferences::remove(const char * key){                 // modified to add an nvs_commit()
same here, please remove trailing comments and the commented out return statement.

2021-07-16 22:51 UTC, beamholder commented
@igrr As I'm new two this whole Github/ Arduino-ESP32 thing, just wondering if this PR is now all good or is there is something else I need to do before it is merged? Thanks.

2021-08-23 16:32 UTC, Xylopyrographer commented
Hi. Has this been merged into the master yet? Anything missing if not? Still figuring out the whole GitHub thing.

On Jul 2, 2021, at 12:26 AM, Ivan Grokhotkov ***@***.***> wrote:


@igrr requested changes on this pull request.

Thanks for the PR @beamholder <https://github.com/beamholder>, it is useful! Some minor requests below...

In libraries/Preferences/src/Preferences.cpp <https://github.com/espressif/arduino-esp32/pull/5309#discussion_r662765845>:

> @@ -53,10 +53,14 @@ bool Preferences::begin(const char * name, bool readOnly, const char* partition_
     return true;
 }
 
-void Preferences::end(){
+void Preferences::end(){                                         // modified to add an nvs_commit()
The comment isn't necessary, as the file change history is visible in git log or git blame, and any commit that has modified a file can be found and reverted if needed. The comments describing the changes (// added by XXX 06/2021) only distract from the purpose of the code.

In libraries/Preferences/src/Preferences.cpp <https://github.com/espressif/arduino-esp32/pull/5309#discussion_r662766131>:

> @@ -74,14 +78,20 @@ bool Preferences::clear(){
         log_e("nvs_erase_all fail: %s", nvs_error(err));
         return false;
     }
-    return true;
+    // return true;                                         // to undo changes: uncomment this line and...
ditto, and please remove this commented out line

In libraries/Preferences/src/Preferences.cpp <https://github.com/espressif/arduino-esp32/pull/5309#discussion_r662766547>:

>      if(!_started){
         return;
     }
+    esp_err_t err = nvs_commit(_handle);                         // to undo changes: delete the lines from here...
Since every other method which does some modifications already calls nvs_commit, is this call actually necessary?

In libraries/Preferences/src/Preferences.cpp <https://github.com/espressif/arduino-esp32/pull/5309#discussion_r662766716>:

>  }
 
 /*
  * Remove a key
  * */
 
-bool Preferences::remove(const char * key){
+bool Preferences::remove(const char * key){                 // modified to add an nvs_commit()
same here, please remove trailing comments and the commented out return statement.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub <https://github.com/espressif/arduino-esp32/pull/5309#pullrequestreview-697859259>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ATMBFQIIEI4SSKLXBMLN5YDTVVL2FANCNFSM467G4BJA>.

2021-08-23 16:52 UTC, igrr approved these changes

2021-08-23 16:54 UTC, igrr commented
@me-no-dev this PR looks good to me, please consider it for the next release.

2021-08-23 18:23 UTC, merged

2021-08-23 18:24 UTC, me-no-dev commented
@igrr @beamholder done :)

2021-08-23 20:05 UTC, Xylopyrographer commented
Whoot! Thank-you.

On Aug 23, 2021, at 12:24 PM, Me No Dev ***@***.***> wrote:


@igrr <https://github.com/igrr> @beamholder <https://github.com/beamholder> done :)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub <https://github.com/espressif/arduino-esp32/pull/5309#issuecomment-904007323>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ATMBFQNAT3PYA44FKL2F5I3T6KG5FANCNFSM467G4BJA>.