[Examples] WiFi and Ethernet examples organization
espressif/arduino-esp32 pull request #5830
Opened 2021-11-02 12:16 UTC by pedrominatel

## Summary

WiFi and Ethernet examples organization. Two folders were created for WiFi and Ethernet examples as well the library name from `WiFi` to `WiFi and Ethernet`.

```
WiFi and Ethernet
  - Ethernet
  - WiFi
```

## Impact

WiFi examples now are in a different folder location. This may cause some impacts on external references to the examples.

2021-11-02 12:17 UTC, pedrominatel commented
PTAL @me-no-dev and evaluate the risks and pros and cons of this change.

2021-11-02 12:33 UTC, me-no-dev commented
There are no risks other than maybe breaking some links somewhere on the web.

2021-11-02 19:22 UTC, Rotzbua requested changes

2021-11-02 19:22 UTC, Rotzbua commented on libraries/WiFi/library.properties
> +name=WiFi and Ethernet
This breaks dependencies, do not change the name.

2021-11-04 12:43 UTC, pedrominatel commented
PTAL @me-no-dev

2021-11-04 14:08 UTC, merged