[DOCS] Writing a new Arduino documentation about GPIO
espressif/arduino-esp32 pull request #5894
Opened 2021-11-16 01:54 UTC by halyssonJr

----------------------------------------------------------------------------------------------------------------------------------------------------
### Checklist

1. [ ] Created five sections (About, GPIO Configuration, API, Simulation and Exemple Code)
2. [ ] Created simulation application 
----------------------------------------------------------------------------------------------------------------------------------------------------

## Summary
Arduino Documentation for GPIO 

## Impact
None

@pedrominatel

2021-11-16 01:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=5894) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=5894) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=5894) it.</sub>

2021-11-16 08:20 UTC, pedrominatel commented
@halyssonJr first things first, remove the build folder. I'll check why the `.gitignore` is still considering the `_build` folder when adding the files.

2021-11-16 12:09 UTC, atanisoft commented on docs/source/api/gpio.rst
> +    void piMode(uint8_t pin, uint8_t mode);
typo: piMode -> pinMode

2021-11-16 12:09 UTC, atanisoft commented on docs/source/api/gpio.rst
> +  If pin not set to ``OUTPUT`` on  pinMode(), may do not work correct.
Remove "do" from the second half of the sentence

2021-11-16 12:25 UTC, halyssonJr commented on docs/source/api/gpio.rst
> +    void piMode(uint8_t pin, uint8_t mode);
Sorry about that, i will be fix

2021-11-16 12:26 UTC, pedrominatel commented
@halyssonJr please be aware of not adding the unrelated folders and files of your build and environment to the commit. Add only the files that you are working on.

Can you clarify why you've changed the `docs/source/conf.py` file?

2021-11-16 12:33 UTC, halyssonJr commented
> @pedrominatel, maybe i just have uncommented, but not made any changes directly  to the `docs/source/conf.py` file?

2021-11-16 12:48 UTC, VojtechBartoska submitted a review, later dismissed

2021-11-16 12:48 UTC, VojtechBartoska commented on docs/source/api/gpio.rst
> +A fetures of this peripheral relates with largely quantity pins available on chip, also being
typo: fe**a**tures

2021-11-16 15:45 UTC, pedrominatel requested changes
PTAL at my considerations.

2021-11-16 17:12 UTC, halyssonJr commented on docs/source/api/gpio.rst
> +This application helps understand concepts using dynamic simulation provide by `Wokwi`_, test the gpio code and start.
Ok, thanks

2021-11-17 02:44 UTC, halyssonJr commented
@pedrominatelI,  I try to split my commit. So I can't upload just the files I changed. In the next PR I will fix these problems

2021-11-22 12:52 UTC, pedrominatel commented
@halyssonJr your PR is messed. You were supposed to edit only one file but now you have 191!

If you need help to understand the Git flow I'll be glad to help. Currently, your PR is not following the expectations and cant be reviewed. Ping me later if you need help.

2021-12-13 13:19 UTC, pedrominatel commented
@halyssonJr please take a look at my modifications.

2021-12-13 14:54 UTC, VojtechBartoska approved these changes
Overall looks good. Found only one small typo.

2021-12-13 14:54 UTC, VojtechBartoska commented on docs/source/api/gpio.rst
> +This function will return the logical state of the selecetd pin as ``HIGH`` or ``LOW``.
typo: select**e**d

2021-12-14 13:39 UTC, merged