[DOCS] Editing usage of Arduino as a component in ESP-IDF
espressif/arduino-esp32 pull request #5896
Opened 2021-11-16 14:21 UTC by P-R-O-C-H-Y

## Summary
Fixed link to lib-builder.
Divided "usage" to 2 options (in 1 you have to change main.c to main.cpp).
Some styling fixes.

## Impact
None.

2021-11-16 14:26 UTC, VojtechBartoska commented
included in #5839

2021-11-16 15:36 UTC, VojtechBartoska approved these changes

2021-11-16 15:45 UTC, pedrominatel requested changes
PTAL at my considerations.

2021-11-16 15:45 UTC, pedrominatel commented on docs/source/esp-idf_component.rst
> +- Create blank idf project (use sample_project from /examples/get-started) or choose one of the examples.
idf -> ESP-IDF. Usually, we use ESP-IDF in capital letters as our official naming rule.

2021-11-16 15:45 UTC, pedrominatel commented on docs/source/esp-idf_component.rst
> +Option 2. Using IDF appmain()
ESP-IDF app_main()

2021-11-19 08:34 UTC, pedrominatel approved these changes

2021-11-19 08:35 UTC, pedrominatel commented
LGTM @P-R-O-C-H-Y. Thank you!

2021-11-22 13:37 UTC, merged