updated Deneyap boards pin_arduino.h files
espressif/arduino-esp32 pull request #7338
Opened 2022-10-10 13:43 UTC by zeynepdicle

*By completing this PR sufficiently, you help us to review this Pull Request quicker and also help improve the quality of Release Notes*

### Checklist
1. [ ] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
2. [ ] Please provide related links (*eg. Issue which will be closed by this Pull Request*)
3. [ ] Please **update relevant Documentation** if applicable
4. [ ] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)

*This entire section above can be deleted if all items are checked.*

-----------
## Description of Change
Please describe your proposed Pull Request and it's impact.

## Tests scenarios
Please describe on what Hardware and Software combinations you have tested this Pull Request and how.

(*eg. I have tested my Pull Request on Arduino-esp32 core v2.0.2 with ESP32 and ESP32-S2 Board with this scenario*)

## Related links
Please provide links to related issue, PRs etc.

(*eg. Closes #number of issue*)

2022-10-19 10:52 UTC, P-R-O-C-H-Y requested changes
Please just fix missing new line at the end of the file in [variants/deneyapmini/pins_arduino.h](https://github.com/espressif/arduino-esp32/pull/7338/files#diff-9de5913e149ceaa63e374882a16581519c92bc5a6661514312a38fc372326603) and [variants/deneyapkartg/pins_arduino.h](https://github.com/espressif/arduino-esp32/pull/7338/files#diff-5634121c78fad9825ddfe89d58fc6f2c4891c3816975ceb3fb1d28aa51934767).
After that will be ready to be merged :)

2022-11-02 08:38 UTC, zeynepdicle commented
> Please just fix missing new line at the end of the file in [variants/deneyapmini/pins_arduino.h](https://github.com/espressif/arduino-esp32/pull/7338/files#diff-9de5913e149ceaa63e374882a16581519c92bc5a6661514312a38fc372326603) and [variants/deneyapkartg/pins_arduino.h](https://github.com/espressif/arduino-esp32/pull/7338/files#diff-5634121c78fad9825ddfe89d58fc6f2c4891c3816975ceb3fb1d28aa51934767). After that will be ready to be merged :)

fixed

2022-11-02 11:13 UTC, P-R-O-C-H-Y commented
> 

@zeynepdicle Now there are missing new lines in more files.

2022-11-03 05:44 UTC, zeynepdicle commented
> @zeynepdicle Now the new line at the end of file is missing in all pins_arduino.h files you changed. Please fix it.

Sorry @P-R-O-C-H-Y I don't understand. Which lines is missing ?

2022-11-03 10:29 UTC, P-R-O-C-H-Y reviewed
Add new line at the end of each pins_arduino.h file you edited.

2022-11-03 10:29 UTC, P-R-O-C-H-Y commented on variants/deneyapkart/pins_arduino.h
> +#endif /* Pins_Arduino_h */
No newline at the end of file.

2022-11-03 10:29 UTC, P-R-O-C-H-Y commented on variants/deneyapkart1A/pins_arduino.h
> +#endif /* Pins_Arduino_h */
No newline at the end of file.

2022-11-03 10:29 UTC, P-R-O-C-H-Y commented on variants/deneyapkartg/pins_arduino.h
>  #endif /* Pins_Arduino_h */
No newline at the end of file.

2022-11-03 10:29 UTC, P-R-O-C-H-Y commented on variants/deneyapmini/pins_arduino.h
>  #endif /* Pins_Arduino_h */
No newline at the end of file.

2022-11-07 13:52 UTC, zeynepdicle commented
is that true ?  @P-R-O-C-H-Y

2022-11-07 14:22 UTC, P-R-O-C-H-Y approved these changes

2022-11-07 14:23 UTC, P-R-O-C-H-Y commented
> is that true ? @P-R-O-C-H-Y

Thanks for fixing, will merge asap as CI passes again :)

2022-11-07 14:37 UTC, merged