Web server simplifications and handers
espressif/arduino-esp32 pull request #7429
Opened 2022-11-04 20:55 UTC by dirkx

Draft proposal to simplify the authentication code in de webserver (and potentially also derisk it); and to also allow for richer authentication; such as with multiple usernames and passwords, the use of Time based one-time passwords or typical IoT bearer tokens. Also adds a number of extra examples - including one that uses an authentication cookie.

Has been tested on ESP-8266 and ESP-32.

PR is primarily to solicited feedback as to wether this is useful to the community.

2023-05-06 15:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=7429) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=7429) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: SuGlider<br/>:x: dirkx<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=7429) it.</sub>

2023-12-11 12:01 UTC, Jason2866 commented
With the changes a simple Webserver now includes mbedtls software libs. This increases code size a lot. Actually the md5 routine from mbedtls is used which is in all MCUs a routine which is embedded in ROM and does not increase code size.

2023-12-11 12:03 UTC, dirkx commented
Ok - so your estimate is that by replacing md5 by the rom routines - we can totally remove the need for mbedtls ? Correct ? If so - happy to give that a try.

2023-12-11 12:58 UTC, Jason2866 commented
Yes, see this change https://github.com/espressif/arduino-esp32/pull/8667

2023-12-20 17:21 UTC, lucasssvaz requested changes
I think this is a very nice improvement but needs some small fixes first, mainly the mbedtls overhead and the crashing when using a bearer. Please also fix the conflicts to update do 3.0.0

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/ESP32/examples/MD5Builder/MD5Builder.ino
> +}
```suggestion
}

```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/examples/HttpAuthCallback/HttpAuthCallback.ino
> +}
```suggestion
}

```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/examples/HttpAuthCallbackInline/HttpAuthCallbackInline.ino
> +}
```suggestion
}

```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/examples/HttpAuthOneTimePassword/HttpAuthOneTimePassword.ino
I think this example would be more useful/proper if it was provided by the OTP library and not the arduino core.

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/examples/HttpAuthOneTimePasswordNaive/HttpAuthOneTimePasswordNaive.ino
I think this example would be more useful/proper if it was provided by the OTP library and not the arduino core.

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/examples/HttpBasicAuthSHA1/HttpBasicAuthSHA1.ino
> +}
```suggestion
}

```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/examples/HttpBasicAuthSHA1orBearerToken/HttpBasicAuthSHA1orBearerToken.ino
> +
```suggestion
```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/examples/HttpBasicAuthSHA1orBearerToken/HttpBasicAuthSHA1orBearerToken.ino
> +/// We have two options - we either come in with a bearer
```suggestion
//  We have two options - we either come in with a bearer
```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/examples/HttpBasicAuthSHA1orBearerToken/HttpBasicAuthSHA1orBearerToken.ino
> +}
```suggestion
}

```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/examples/HttpBasicAuthSHA1orBearerToken/HttpBasicAuthSHA1orBearerToken.ino
> +//    curl https://myesp.com/  -H "Authorization: Bearer SecritToken"
Using this command with the proper IP makes the application crash with a Load Exception on `WebServer::authenticateBasicSHA1`

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/src/WebServer.cpp
> +#include "mbedtls/base64.h"
As @Jason2866 said, I don't think it is a good idea to the WebServer to depend on mbedtls. Maybe a minimal version of the functions needed could be provided ?

2023-12-20 17:21 UTC, lucasssvaz commented on cores/esp32/HEXBuilder.h
> +#define __ESP8266_HEX_BUILDER__
```suggestion
#ifndef HEXBuilder_h
#define HEXBuilder_h
```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/examples/HttpAuthCallback/HttpAuthCallback.ino
> +  Serial.begin(115200);
```suggestion
  Serial.begin(115200);
  while (!Serial) { delay(10); }
```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/examples/HttpAuthCallbackInline/HttpAuthCallbackInline.ino
> +  Serial.begin(115200);
```suggestion
  Serial.begin(115200);
  while (!Serial) { delay(10); }
```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/examples/HttpBasicAuthSHA1/HttpBasicAuthSHA1.ino
> +
```suggestion
```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/WebServer/examples/HttpBasicAuthSHA1/HttpBasicAuthSHA1.ino
> +  Serial.begin(115200);
```suggestion
  Serial.begin(115200);
  while (!Serial) { delay(10); }
```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/ESP32/examples/HEXBuilder/HEXBuilder.ino
> +  delay(100);
```suggestion
  while (!Serial) { delay(10); }
```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/ESP32/examples/MD5Builder/MD5Builder.ino
> +  delay(100);
```suggestion
  while (!Serial) { delay(10); }
```

2023-12-20 17:21 UTC, lucasssvaz commented on libraries/ESP32/examples/MD5Builder/MD5Builder.ino
> +void setup() {
```suggestion

void setup() {
```

2024-01-16 01:59 UTC, lucasssvaz reviewed
@SuGlider @P-R-O-C-H-Y PR fixed and ready for review

2024-01-16 02:00 UTC, lucasssvaz approved these changes

2024-01-16 09:48 UTC, me-no-dev commented on libraries/WebServer/src/WebServer.cpp
> +bool WebServer::authenticateBasicSHA1(const char * _username, const char * _sha1Base64orHex) {
this method seems to have indentation issues. There are some more throughout the file as well, but fix only what has been changed

2024-01-16 09:49 UTC, me-no-dev commented on libraries/WebServer/src/WebServer.cpp
> +	return WebServer::authenticate([_username,_password](HTTPAuthMethod mode, String username, String params[])->String * {
indentation

2024-01-16 13:49 UTC, merged