Draft: Multi threading examples (tasks, queues, semaphores, mutexes)
espressif/arduino-esp32 pull request #7660
Opened 2023-01-04 13:17 UTC by PilnyTomas

Moved the original ESP32/FreeRTOS example to a new pseudo library (no actual source code) called MultiThreading.
The original example was renamed to BasicMultiThreading demonstrating the most basic use of tasks.
New examples will be added demonstrating the use of queues, semaphores, and mutexes.
As part of this PR I will also adhere to the new standards - add readme files, headers, etc stated here https://github.com/espressif/arduino-esp32/issues/7659

2023-01-06 22:31 UTC, mrengineer7777 commented
Queue.ino example may be helpful in a future project.  Thanks!

2023-01-19 15:02 UTC, pedrominatel commented on libraries/MultiThreading/examples/BasicMultiThreading/BasicMultiThreading.ino
> +// Please read file README.md in the folder containing this example.
Please add the header.

```
/* Basic Multi Threading Arduino Example
   This example code is in the Public Domain (or CC0 licensed, at your option.)
   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
```

Same for the others.

2023-01-19 15:02 UTC, pedrominatel commented on libraries/MultiThreading/examples/Semaphore/Semaphore.ino
> +// Please read file README.md in the folder containing this example.
This example is not working on my ESP32 board.

`Backtrace: 0x40087e51:0x3ffb9150 0x40084557:0x3ffb9230 0x400d2343:0x3ffb9270 0x400d157d:0x3ffb9290 0x400d1903:0x3ffb92b0 0x400d1915:0x3ffb92d0 0x400d12b3:0x3ffb92f0`

2023-01-26 15:14 UTC, P-R-O-C-H-Y requested changes
@PilnyTomas Please take a look on my comments.

2023-01-26 15:14 UTC, P-R-O-C-H-Y commented on libraries/MultiThreading/examples/BasicMultiThreading/BasicMultiThreading.ino
> +
This example is not working for me on ESP32-S3 devkitC. Can you please test that? 
Analog pin was changed of course.

```
Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception). 
Debug exception reason: Stack canary watchpoint triggered (Analog Read) 

Backtrace: 0x4037d1bc:0x3fced4e0 0x4037bdfd:0x3fced520 0x4037a71c:0x3fced550 0x4037a712:0xa5a5a5a5 |<-CORRUPTED
```

2023-01-26 15:14 UTC, P-R-O-C-H-Y commented on libraries/MultiThreading/examples/BasicMultiThreading/README.md
> +* ESP32-C3 Datasheet: [Link to datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-c3_datasheet_en.pdf)
Please add ESP32-S3 datasheet link to all README files. PR https://github.com/espressif/arduino-esp32/pull/7738.

2023-01-26 15:17 UTC, P-R-O-C-H-Y commented
One more comment, `Semaphore.ino` is missing Readme. As you did nice readme with theory and explanation, it would be great to have it for semaphore too even it's simpler.

2023-01-30 10:07 UTC, PilnyTomas commented
> One more comment @PilnyTomas, `Semaphore.ino` is missing Readme. As you did nice readme with theory and explanation, it would be great to have it for semaphore too even it's simpler.

I just forgot to add it :D

2023-01-31 14:41 UTC, pedrominatel approved these changes
LGTM

2023-02-01 09:38 UTC, P-R-O-C-H-Y approved these changes
All examples are now working :)
Just please @PilnyTomas add the ESP32-S3 data sheets link into all readme files. Thanks

2023-02-01 10:17 UTC, P-R-O-C-H-Y approved these changes
LGTM!

2023-02-06 16:53 UTC, me-no-dev commented
I will suggest to move all new examples into `libraries/ESP32/examples/FreeRTOS/` folder. They do not need to be in their own library

2023-02-08 10:40 UTC, me-no-dev requested changes
Change location of examples to `libraries/ESP32/examples/FreeRTOS/`

2023-02-08 15:42 UTC, me-no-dev approved these changes

2023-02-08 15:42 UTC, merged