Added the example guideline and template
espressif/arduino-esp32 pull request #7665
Opened 2023-01-05 14:34 UTC by pedrominatel

## Description of Change
This PR adds the example guideline and template.

## Tests scenarios
N/A

## Related links
N/A

2023-01-06 22:22 UTC, mrengineer7777 reviewed
LGTM

2023-01-09 12:41 UTC, P-R-O-C-H-Y requested changes
PTAL @pedrominatel.

2023-01-09 12:41 UTC, P-R-O-C-H-Y commented on docs/source/contributing.rst
> +All the source files must include the header with the example name and license, if applicable. You can change this header as you with, but it will be reviewed by the community and may not be accepted
... You can change this header as you **wish**, ...

2023-01-09 12:41 UTC, P-R-O-C-H-Y commented on docs/source/contributing.rst
> +Inline comments are important if the example contains complex algorithms os specific configuration that the user needs to change.
... complex algorithms **or** specific ...

2023-01-09 12:41 UTC, P-R-O-C-H-Y commented on docs/source/contributing.rst
> +  * If you are contributing by adding a new example, please use the `Arduino style guide`_ and the example guideline below.
Missing empty line between:
`* Example contributions are also welcome.`
and
`* If you are contributing by adding a new example, please use the...`

2023-01-09 15:09 UTC, pedrominatel commented
Thanks for the review, @P-R-O-C-H-Y.

2023-01-09 15:32 UTC, P-R-O-C-H-Y approved these changes
LGTM!

2023-01-10 16:22 UTC, VojtechBartoska approved these changes
In general, the proposal is nice. I'm sharing just few more likely format and language suggestions.

2023-01-10 16:22 UTC, VojtechBartoska commented on docs/source/contributing.rst
> +* Is the contribution entirely your own work, or is it already licensed under an LGPL 2.1 compatible Open Source License? If not, we, unfortunately, cannot accept it.
This sentence is a bit awkward.

Suggestion:
If it's not, we unfortunately cannot accept it.

2023-01-10 16:22 UTC, VojtechBartoska commented on docs/source/contributing.rst
> +* Is the code adequately commented on to people understand how it is structured?
Again, this sentence is a bit awkward.

Suggestion:

Is the code adequately commented so others can understand how it is structured?

2023-01-10 16:22 UTC, VojtechBartoska commented on docs/source/contributing.rst
>  Once the Pull Request is ready to merge, it will first be merged into our internal git system for in-house automated testing.
Optionally, we can put phase "in-house" into quotation marks as it's our "naming".

2023-01-10 16:22 UTC, VojtechBartoska commented on docs/source/contributing.rst
> +* Check if your example proposal has no similarities to the project
I will add here this to make it more clear:

* Check if your example proposal has no similarities to the project **(already existing examples)**

2023-01-10 16:22 UTC, VojtechBartoska commented on docs/source/contributing.rst
> +Additionally, you can add some description about the example, links to the documentation, or the author's name. Just have in mind to keep it simple and short.
I will change here the word of Additionally to "Ideally" :) 

Maybe add link to "readme.md" of the example?

2023-01-10 16:22 UTC, VojtechBartoska commented on docs/source/contributing.rst
What about addding here a link to nicely commented example?

2023-01-10 16:22 UTC, VojtechBartoska commented on docs/source/contributing.rst
_I will add one more sentence:_

Brief and clear inline comments are really helpful for the example understanding and it's fast usage.

2023-01-16 14:29 UTC, pedrominatel commented
PTAL, @VojtechBartoska and merge if everything is ok.

2023-01-17 14:28 UTC, merged

2023-01-19 15:56 UTC, P-R-O-C-H-Y commented on libraries/ESP32/examples/Template/ExampleTemplate/README.md
>  * Arduino-ESP32 Official Repository: [espressif/arduino-esp32](https://github.com/espressif/arduino-esp32)
@pedrominatel As this part was not edited and hidden in the PR, we should add ESP32-S3 datasheet link too. To have it in all future example READMEs.