fixed the function header
espressif/arduino-esp32 pull request #7674
Opened 2023-01-07 04:36 UTC by bytiful

## Description of Change
fixed the function header ftom ledcSetup to  sigmaDeltaSetup

## Tests scenarios
I have tested my Pull Request on Arduino-esp32  with ESP32-S3 Board

2023-01-07 04:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=7674) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=7674) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=7674) it.</sub>

2023-01-09 12:05 UTC, P-R-O-C-H-Y requested changes
Hi @bytiful, Thank you for finding that out. Please take a look on my comment, so we can merge it fixed completely.

2023-01-25 11:02 UTC, VojtechBartoska commented
Any updates @bytiful?

2023-02-01 10:26 UTC, P-R-O-C-H-Y approved these changes

2023-02-06 13:09 UTC, merged