Supporting ETag http headers on static files
espressif/arduino-esp32 pull request #7687
Opened 2023-01-09 16:47 UTC by mathertel

The ETag (or entity tag) HTTP header specified the version of the returned resource.
This is done by the default implementation by calculating the md5 checksuom of the file content.
A custom ETag calculation can be passed as an option.

This allows client side caching to be more efficient and save bandwidth.

The implementation is taken from esp8266/Arduino and is compatible with the WebServer implementation for esp8266.
where it was implemented by @imwhocodes and me (@mathertel).

The `WebServer` now include the methon `enableETag(bool enable, ETagFunction fn = nullptr)`
to enable and disable ETag Headers for a server.

The `StaticRequestHandler` calculates the ETag value when enabled and checks / populates the header.

An optional ETag calculation function can be passed to enableETag (e.g. to provide different algorithms).

## Example

The **WebServer Example** illustrates using the ETag function.

It is using the "last change date" of the filesystem to create ETags wich is more efficient.

It is available on some file systems implementations (LittleFS, FSFAT but not SPIFFS)
and requires NTP to provide a current datetime.

## Some Doku

### about http ETags

ETags are "hints" delivered with a web response in the `ETag` http-Header to the client.

This hint value is added to further requests to the same resource in the .`If-None-Match` Header.
Hereby the server can check if the client should still use the version in the cache or needs an update.

The web server does not send a full response and file content when the content was not changed
but just returns a `304 Not Modified` status to the client resulting in much smaller network packages.

In the cases when the clients will request for the same resources multiple times in a row
the server-side checksum check is a lot more effective than transferring the bytes over the network.

As this is not always true there is an extended option to inject a function that behavior can be customized and tailored to the specific requirements.

### enabling ETag support

To enable this in the embedded web server the enableETag() can be used.
(next to enableCORS)

In the simplest version just call enableETag(true) to enable the internal ETag generation that calcs the hint using a md5 checksum in base64 encoded form. This is an simple approach that adds some time for calculation on every request but avoids network traffic.

The headers will look like:

``` txt
If-None-Match: "GhZka3HevoaEBbtQOgOqlA=="
ETag: "GhZka3HevoaEBbtQOgOqlA=="
```

### ETag support customization

The enableETag() function has an optional second optional parameter to provide a function for ETag calculation of files.

The function enables eTags for all files by using calculating a value from the last write timestamp:

``` cpp
server.enableETag(true, [](FS &fs, const String &path) -> String {
  File f = fs.open(path, "r");
  String eTag = String(f.getLastWrite(), 16);  // use file modification timestamp to create ETag
  f.close();
  return (eTag);
});
```

The headers will look like:

``` txt
ETag: "63bbaeb5"
If-None-Match: "63bbaeb5"
```

2023-01-25 11:04 UTC, VojtechBartoska commented
Thanks for nice and complete PR @mathertel! We'll review it soon.

2023-01-25 14:10 UTC, PilnyTomas requested changes
@mathertel nice work!
Would it be easy to add some extended feedback on the file upload? For example in serial output mention the file name and size and/or enable downloading it back.
Also please modify the `.ino` header and `README.md` so that it is using our [new template](https://github.com/espressif/arduino-esp32/tree/563804706b0ad76b6eae433e342f1d8790dacfcd/libraries/ESP32/examples/Template/ExampleTemplate)
Otherwise LGTM.

2023-02-01 12:53 UTC, P-R-O-C-H-Y commented
Any updates @mathertel on @PilnyTomas 's comment?

2023-02-01 21:03 UTC, mathertel commented
please review.

2023-02-02 10:40 UTC, PilnyTomas commented
@mathertel Thanks for the addition. Please make sure that when someone tries to upload a too large file it doesn't run away with a looped message:
```
./components/esp_littlefs/src/littlefs/lfs.c:584:error: No more free space 385
./components/esp_littlefs/src/littlefs/lfs.c:584:error: No more free space 385
./components/esp_littlefs/src/littlefs/lfs.c:584:error: No more free space 385
And to the infinity ...
```
For small files, the messages are enough.

2023-02-26 10:07 UTC, mathertel commented
@PilnyTomas : All implemented as you suggested. Please Review or give some feedback.

2023-03-04 10:28 UTC, mathertel commented
This is a compatibility request to ESP8266 to easy migration to ESP32 (C3).
Would be welcome to include it in the next version.
@PilnyTomas : All implemented as you suggested. Please Review or give some feedback.
@P-R-O-C-H-Y : Who can do the review when @PilnyTomas doesn't find the time ?

2023-03-09 09:46 UTC, VojtechBartoska commented
hello @mathertel, thanks for the updates. We'll review your PR soon.

2023-03-24 17:07 UTC, PilnyTomas approved these changes
Hi, sorry for the delay, I had some happy changes in my life, so I took a few weeks off.
Thank you for your updates.
I would love to see a different message when the upload fails - instead of "finished" there could be something like "Upload failed"
It isn't necessary - just nice to have, so I approve the PR.

2023-05-06 15:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=7687) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=7687) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=7687) it.</sub>

2023-11-29 12:44 UTC, P-R-O-C-H-Y requested changes
@mathertel Please add a empty `.skip.esp32h2` file to your example folder to fix failing CI.

2023-11-29 19:00 UTC, mathertel commented
> @mathertel Please add a empty `.skip.esp32h2` file to your example folder to fix failing CI.

done.

2023-11-29 19:00 UTC, lucasssvaz approved these changes
Small nitpick but LGTM

2023-11-29 19:17 UTC, me-no-dev commented on libraries/WebServer/examples/WebServer/data/files.htm
> +</html>
I think you fixed `index.htm` (which was also to be fixed), but forgot to also add a line at the end in `files.htm` as well

2023-11-30 18:52 UTC, merged