Added methods + example to retrive local MAC for BT
espressif/arduino-esp32 pull request #7778
Opened 2023-01-31 13:18 UTC by PilnyTomas

It was not easy or obvious how to retrieve a MAC address of a local BT device.
There is an IDF function `esp_bt_dev_get_address` which accomplishes that and is used in this solution.
However, there was no `BluetoothSerial`method that would facilitate this.
This PR adds three new methods, slightly extends the `BTAddress::toString`, and adds a new example `GetLocalMAC` which demonstrates the usage of the new additions.

2023-02-01 09:22 UTC, P-R-O-C-H-Y requested changes
@PilnyTomas please check my comments (typo and format issues), example is working great! Thank for the PR. After fixes it will be ready to merge.

2023-02-01 09:22 UTC, P-R-O-C-H-Y commented on libraries/BluetoothSerial/src/BTAddress.cpp
> + * When the parameter `caputal` == true the format uses capital letters:
Fix typo ... parameter **`capital`** == true ...

2023-02-01 09:22 UTC, P-R-O-C-H-Y commented on libraries/BluetoothSerial/src/BTAddress.cpp
> +  }
Align the if/else with spaces to match the format in the function.

2023-02-01 09:22 UTC, P-R-O-C-H-Y commented on libraries/BluetoothSerial/src/BluetoothSerial.cpp
> +}
I have checked that the formatting style isn't the same in whole file, but can you align the spaces as is in the function above?

2023-02-01 10:16 UTC, P-R-O-C-H-Y approved these changes
LGTM!

2023-02-06 12:37 UTC, me-no-dev commented on libraries/BluetoothSerial/src/BTAddress.cpp
> +std::string BTAddress::toString(bool capital) const {
I see that originally the method returns `std::string`, but please change it to Arduino `String` instead.

2023-02-06 12:38 UTC, me-no-dev commented on libraries/BluetoothSerial/src/BluetoothSerial.cpp
> +std::string BluetoothSerial::getBtAddressString() {
Same here `std::string` =>> `String`

2023-02-08 15:45 UTC, me-no-dev commented on libraries/BluetoothSerial/src/BluetoothSerial.h
> +        std::string getBtAddressString();
you forgot to change the type here

2023-02-08 15:46 UTC, me-no-dev commented on libraries/BluetoothSerial/src/BTAddress.h
>  public:
up in the includes, you need to change `#include <string>` to `#include "Arduino.h"`

2023-02-08 15:47 UTC, me-no-dev requested changes
Change include and left over `std::string` in BluetoothSerial.h

2023-02-13 10:32 UTC, me-no-dev approved these changes

2023-02-13 10:32 UTC, merged