getNextFileName(boolean *isDir): get info if filename is a file or dir
espressif/arduino-esp32 pull request #8068
Opened 2023-04-12 14:18 UTC by tueddy

Hi Arduino-ESP32 team,

the FS function `getNextFilename()` has been merged since 2.0.6 and speeds-up directory listing by factor >20 (many files on SD-card).
Thank's for this improvement!

Unfortunately, this function can only be used to a limited extent because it is not possible to distinguish whether the returned name is a file or a directory. This may have been overlooked in PR #7229 , see discussion. 
A concrete use case is an SD card web server that delivers a JSON file/directory structure for given path. 

I have overloaded the function with a new return parameter isDir. This returns true if it is a directory:

```
    String getNextFileName(void);
    String getNextFileName(boolean *isDir);
```

Changes are minimal & this PR should be fully backwards compatible.

Thank's
Dirk

Directory listing in the browser with `openNextFile()`. Loading one directory-level takes 2s:

![Slow](https://user-images.githubusercontent.com/11274319/231485280-392b3dfc-7f70-41a8-bdb2-229f16761a14.gif)

Directory listing in the browser with `getNextFileName(boolean *isDir)`. Loading one directory-level takes 20ms:

![Fast](https://user-images.githubusercontent.com/11274319/231485886-270d044d-ea2d-4a8d-bb39-26d5d3bb7a3f.gif)

2023-04-12 14:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8068) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8068) before we can accept your contribution.<br/><hr/>**tueddy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=8068) it.</sub>

2023-04-14 06:43 UTC, P-R-O-C-H-Y approved these changes
Looks great! Thanks for contribution @tueddy :)
Please submit the CLA to be able to merge this.

2023-04-14 07:43 UTC, tueddy commented
@P-R-O-C-H-Y Thank's for approving!
I had problems signing the CLA beacause my email was missing in first commit.
I have commited a small enhancement, checking for isDir != NULL to avoid a crash.
With this commit i hope the CLA signing was successful now..

2023-04-14 08:19 UTC, P-R-O-C-H-Y requested changes

2023-04-14 08:19 UTC, P-R-O-C-H-Y commented on libraries/FS/src/vfs_api.cpp
> +	}
That check is good for sure. Can you just remove the spaces before the part so its aligned with other code?

2023-04-14 08:20 UTC, P-R-O-C-H-Y commented
@tueddy Seems that CLA is still not signed yet.

2023-04-14 08:49 UTC, tueddy commented
Don't know what's wrong with signing:

![grafik](https://user-images.githubusercontent.com/11274319/231993986-f5c32be1-2703-43a2-b172-c76c6c346db1.png)

2023-04-14 09:04 UTC, P-R-O-C-H-Y commented
Seems that the first commit doesn't know your GITHUB, and that's why this is happening..

<img width="1423" alt="Snímek obrazovky 2023-04-14 v 11 02 46" src="https://user-images.githubusercontent.com/90197375/231998141-6184d536-0a21-4882-8f37-b82227dccbb9.png">

2023-04-14 09:05 UTC, fschrempf commented
> Don't know what's wrong with signing:

I suspect it's because the first of your three commits still has the wrong author/e-mail. You should probably squash the commits into one and fix the authorship.

2023-04-14 09:13 UTC, P-R-O-C-H-Y commented
> > Don't know what's wrong with signing:
> 
> I suspect it's because the first of your three commits still has the wrong author/e-mail. You should probably squash the commits into one and fix the authorship.

That should help. You can do squash yourself on your branch so you will still be the author :)

2023-04-14 13:17 UTC, P-R-O-C-H-Y commented
@tueddy If there is still a problem, it will be faster to close this PR, create new branch and copy the changes there. After that open new PR and ping me to comment and I will approve it ASAP :)

2023-04-14 19:26 UTC, tueddy commented
I will close here & open a new PR..

2023-04-14 19:26 UTC, closed without merging