Add USB MIDI support to libraries/USB
espressif/arduino-esp32 pull request #8166
Opened 2023-05-06 15:56 UTC by EleotleCram

## Description of Change
This PR adds support for USB MIDI to libraries/USB. It wraps the underlying tiny-usb API in an Arduino-like/User-friendly API, similar to the already existing USBHID* classes.

## Tests scenarios
All the examples have been tested using an ESP32-S2 Mini. Please see the related links section for video-proof that it works.

## Related links
* MIDI Music Box Demo - https://youtu.be/JFrc-wSmcus
* MIDI Interface Demo - https://youtu.be/BXG5i55I9s0
* MIDI Controller Demo - https://youtu.be/Y9TLXs_3w1M

2023-05-11 10:42 UTC, me-no-dev commented
Very nice implementation!

- You need to add `USBMIDI.cpp` [here](https://github.com/EleotleCram/arduino-esp32/blob/usb-midi-support/CMakeLists.txt#L114)
- There are also some other build errors reported by CI [here](https://github.com/espressif/arduino-esp32/actions/runs/4902674538/jobs/8845612539?pr=8166#step:5:92)

2023-05-12 11:09 UTC, EleotleCram commented
Thanks!

And I was already suspicious on how silent the _arduino-cli_ output was, I just discovered the `--warnings all` option ;-)
Will fix this shortly.

2023-11-28 22:23 UTC, lucasssvaz approved these changes
Working as expected

2023-11-28 22:23 UTC, lucasssvaz commented on libraries/USB/src/USBMIDI.cpp
> +#define DEFAULT_CN 0
Wouldn't it be better to move this to the beginning of the file ?

2023-11-28 22:23 UTC, lucasssvaz commented on libraries/USB/src/USBMIDI.h
> +    //
```suggestion
    /* Serial MIDI 1.0 interface */

```

2023-11-28 22:23 UTC, lucasssvaz commented on libraries/USB/src/USBMIDI.h
> +    //
```suggestion
    /* USB MIDI 1.0 interface */

```

2023-11-28 22:23 UTC, lucasssvaz commented on libraries/USB/src/USBMIDI.h
> +#define MIDI_CIN_NOTE_OFF 8
This is already merged upstream, could this be deleted ?

2023-11-28 22:23 UTC, lucasssvaz commented on libraries/USB/src/USBMIDI.h
> +    //
```suggestion
    /* User-level API */

```

2023-11-29 11:38 UTC, P-R-O-C-H-Y requested changes
@EleotleCram PTAL on my comments.
Also please add skip files to examples for esp32c6 and esp32h2. 
Thanks! Good job :)

2023-11-29 11:38 UTC, P-R-O-C-H-Y commented on libraries/USB/src/USBMIDI.cpp
> +
Please add check for USB peripheral support as other USB files has.

```suggestion
#if SOC_USB_OTG_SUPPORTED

```

2023-11-29 11:38 UTC, P-R-O-C-H-Y commented on libraries/USB/src/USBMIDI.cpp
> +#endif // CONFIG_TINYUSB_MIDI_ENABLED
Close the #if from above comment
```suggestion
#endif /* CONFIG_TINYUSB_MIDI_ENABLED */
#endif /* SOC_USB_OTG_SUPPORTED */
```

2023-11-29 11:38 UTC, P-R-O-C-H-Y commented on libraries/USB/src/USBMIDI.h
> +
Include the `social_caps.h` and add a check also to header file.

```suggestion
#include "soc/soc_caps.h"
#if SOC_USB_OTG_SUPPORTED
```

2023-11-29 11:38 UTC, P-R-O-C-H-Y commented on libraries/USB/src/USBMIDI.h
> +#endif // CONFIG_TINYUSB_MIDI_ENABLED
Close the #if from above comment.
```suggestion
#endif /* CONFIG_TINYUSB_MIDI_ENABLED */
#endif /* SOC_USB_OTG_SUPPORTED */
```

2023-12-01 09:25 UTC, VojtechBartoska commented
Hello @EleotleCram,

thanks for you PR.

Unfortunately it seems that CLA form did not show up for your first contribution. Can you please check https://cla-assistant.io/ if you have the CLA signed for this repository.

Thanks a lot

2023-12-03 18:28 UTC, EleotleCram commented
@VojtechBartoska AFAIK I already signed the CLA for this repository; when I log in to cla-assistant and I view my signed CLAs it lists this repo.

2023-12-05 08:42 UTC, merged