Add board:  Nebula S3
espressif/arduino-esp32 pull request #8257
Opened 2023-05-26 18:12 UTC by DocMonster7

## Description 
A variant of ESP32-S3 development board created with sole focus on hobbyist with on board IMU which is MPU-6050 and 
WS2812B LED with Battery connector. 

## Schematic 

![Schematic_Nebula V1_2023-05-26](https://github.com/espressif/arduino-esp32/assets/34396385/54f28e9e-bef1-465f-b15b-ab09321ec256)

## Boards

![Nebula s3](https://github.com/espressif/arduino-esp32/assets/34396385/0107ebe4-5d39-4cd5-9700-88727db8beae)

2023-05-26 18:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8257) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8257) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=8257) it.</sub>

2023-05-29 10:55 UTC, P-R-O-C-H-Y requested changes
@DocMonster7 PTAL on my comment.

2023-05-29 10:55 UTC, P-R-O-C-H-Y commented on boards.txt
> +nebulas3.build.board=ESP32S3_DEV
ESP32S3_DEV should be changed to some different name like NEBULAS3.

2023-05-29 10:55 UTC, P-R-O-C-H-Y commented on boards.txt
> +
please just remove this empty line, which is doubled.

2023-05-29 11:08 UTC, DocMonster7 commented
@P-R-O-C-H-Y Please review changes made.

2023-05-29 11:12 UTC, P-R-O-C-H-Y commented
@DocMonster7 It seems you kind of changed whole boards.txt file. Can't load the diffs.
_23,467 additions, 23,467 deletions not shown because the diff is too large. Please use a local Git client to view these changes._

2023-05-29 11:14 UTC, DocMonster7 commented
Sorry about that, I will try to resolve it using my local client and then push the changes instead of the web editor

2023-05-29 11:20 UTC, P-R-O-C-H-Y commented
Looks good now, but please change the board to UPPERCASE -> NebulaS3 to NEBULAS3. Thanks

2023-05-29 11:28 UTC, DocMonster7 commented
I have made the requested changes. Have a look.

2023-05-29 11:31 UTC, P-R-O-C-H-Y approved these changes
All good now :)

2023-05-31 11:33 UTC, merged