BT serial: SSP improvements, added missing events
espressif/arduino-esp32 pull request #8453
Opened 2023-07-24 12:06 UTC by PilnyTomas

Added missing events
Added method to remove cached devices.
Renamed, clarified, and extended usage of SSP API + example
Fixed support for legacy pairing (fixed PIN) - must use as IDF component and disable `CONFIG_BT_SSP_ENABLED`
related https://github.com/espressif/arduino-esp32/issues/4566

Including fix for #8448

2023-08-22 20:14 UTC, lucasssvaz requested changes
The review is mostly nit-picks. I couldn't get the BT to work with the provided instructions. Please double check if it is working or my setup is faulty. Also squash the commits at the end, please.

2023-08-22 20:14 UTC, lucasssvaz commented on libraries/BluetoothSerial/examples/SerialToSerialBT_SSP/SerialToSerialBT_SSP.ino
> +    delay(20);
```suggestion
    SerialBT.write(Serial.read());
  }
  if (SerialBT.available()){
    Serial.write(SerialBT.read());
  }
  delay(20);
```

2023-08-22 20:14 UTC, lucasssvaz commented on libraries/BluetoothSerial/examples/SerialToSerialBT_SSP/SerialToSerialBT_SSP.ino
> +  }else{
```suggestion
  } else {
```

2023-08-22 20:14 UTC, lucasssvaz commented on libraries/BluetoothSerial/examples/bt_remove_paired_devices/bt_remove_paired_devices.ino
> +  }else{
```suggestion
  } else {
```

2023-08-22 20:14 UTC, lucasssvaz commented on libraries/BluetoothSerial/examples/bt_remove_paired_devices/bt_remove_paired_devices.ino
> +          }else{
```suggestion
          } else {
```

2023-08-22 20:14 UTC, lucasssvaz commented on libraries/BluetoothSerial/examples/bt_remove_paired_devices/bt_remove_paired_devices.ino
> +void loop() {}
```suggestion
void loop() {}

```

2023-08-22 20:14 UTC, lucasssvaz commented on libraries/BluetoothSerial/examples/bt_remove_paired_devices/bt_remove_paired_devices.ino
> +void loop() {}
Keep the newline character so the source file has a posix compliant ending

2023-08-22 20:14 UTC, lucasssvaz commented on libraries/BluetoothSerial/src/BluetoothSerial.cpp
> +            else {
```suggestion
            } else {
```

2023-08-22 20:14 UTC, lucasssvaz commented on libraries/BluetoothSerial/src/BluetoothSerial.cpp
> +    }else{
```suggestion
    } else {
```

2023-08-22 20:14 UTC, lucasssvaz commented on libraries/BluetoothSerial/src/BluetoothSerial.cpp
> +            }else{
```suggestion
            } else {
```

2023-08-24 11:02 UTC, PilnyTomas commented on libraries/BluetoothSerial/README.md
> +Those examples are preset to work out-of-the-box but they should be scalable to connect multiple Slaves to the Master.
Well, this is really strange... for me, it is also not working. However, I can connect to the slave from my smartphone.

2023-08-24 12:43 UTC, lucasssvaz commented on libraries/BluetoothSerial/README.md
> +Those examples are preset to work out-of-the-box but they should be scalable to connect multiple Slaves to the Master.
Yeah, using my smartphone I also managed to connect. There might be something weird happening in the master sketch.

2023-10-05 15:11 UTC, me-no-dev commented
Closed in favor of https://github.com/espressif/arduino-esp32/pull/8723

2023-10-05 15:11 UTC, closed without merging