Create pins_arduino.h for heltek wireless tracker
espressif/arduino-esp32 pull request #8464
Opened 2023-07-27 12:30 UTC by codeadventure20

*By completing this PR sufficiently, you help us to review this Pull Request quicker and also help improve the quality of Release Notes*

### Checklist
1. [ ] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
2. [ ] Please provide related links (*eg. Issue which will be closed by this Pull Request*)
3. [ ] Please **update relevant Documentation** if applicable
4. [ ] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)

*This entire section above can be deleted if all items are checked.*

-----------
## Description of Change
Create pins_arduino.h for heltek wireless tracker

## Tests scenarios
Please note that I'm not 100% sure of what I'm doing.

I used it in PlatformIO on the Heltek Wireless Tracker and works ok. but I didn't used the espressif directly and I'm not sure how to do so. 
I've been advised by PlatformIO developer to submit this file first: https://github.com/platformio/platform-espressif32/issues/1148
Also, we might need the latest release of the WIFI kit series (https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series)

PlatformIO also requires this file:

boards\heltec_wireless_tracker.json

{
  "build": {
    "arduino": {
      "ldscript": "esp32s3_out.ld",
      "partitions": "default.csv"
    },
    "core": "esp32",
    "extra_flags": [
      "-DWireless_Track",
      "-DARDUINO_USB_MODE=1",
      "-DARDUINO_RUNNING_CORE=1",
      "-DARDUINO_EVENT_RUNNING_CORE=1"      
     ],
    "f_cpu": "240000000L",
    "f_flash": "80000000L",
    "flash_mode": "qio",
    "hwids": [
      [
        "0x303A",
        "0x1001"
      ]
    ],
    "mcu": "esp32s3",
    "variant": "heltec_wireless_tracker"
  },
  "connectivity": [
    "wifi",
    "bluetooth",
    "lora",
    "gps"
  ],
  "debug": {
    "openocd_target": "esp32s3.cfg"
  },
  "frameworks": [
    "arduino",
    "espidf"
  ],
  "name": "Heltec Wireless Tracker",
  "upload": {
    "flash_size": "8MB",
    "maximum_ram_size": 327680,
    "maximum_size": 8388608,
    "require_upload_port": true,
    "speed": 1036800
  },
  "url": "https://heltec.org/project/wireless-tracker/",
  "vendor": "Heltec"
}

## Related links
https://github.com/platformio/platform-espressif32/issues/1148
https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/issues/193

2023-07-27 12:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8464) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8464) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=8464) it.</sub>

2023-08-06 04:03 UTC, lyusupov commented
@codeadventure20 
this `pins_arduino.h` pins definition does not match to the one used in the actual  schematic file(s) for the **Heltec Wireless Tracker** product:
* https://resource.heltec.cn/download/Wireless_Tracker
* http://community.heltec.cn/t/schematic-of-new-heltec-esp32-s3-wireless-tracker-product/13308

2023-08-29 10:35 UTC, P-R-O-C-H-Y requested changes
@codeadventure20 The board does not exist in boards.txt file and without that is useless.
Please add define the board in the board.txt file to make this PR able to be merged.

Also please check the pins as I found some are wrong and same did @lyusupov. Thanks

2023-08-30 12:08 UTC, VojtechBartoska commented
Closing this PR as it's missing some info. If you want to add support for this board please open the new Pull Request. Thanks @codeadventure20

2023-08-30 12:08 UTC, closed without merging