added lilygo t-display (esp32-based) board definition
espressif/arduino-esp32 pull request #8533
Opened 2023-08-15 12:00 UTC by PBrunot

## Description of Change

This change adds a new board lilygo-t-display based on esp32. Board variants have 4 MB or 16 MB flash memory. All boards come with a TFT display. This board is the predecessor to the already included lilygo-t-display-s3.

[Manufacturer Board webpage](https://www.lilygo.cc/products/lilygo%C2%AE-ttgo-t-display-1-14-inch-lcd-esp32-control-board)

[Pinmap](https://github.com/Xinyuan-LilyGO/TTGO-T-Display/blob/master/image/pinmap.jpg)

## Tests scenarios

I have tested my pull request with a Lilygo TDisplay HW rev 1.1 by configuring PlatformIO to use the platform in https://github.com/PBrunot/arduino-esp32#feature-lilygo-tdisplay as framework for arduino-esp32, and uploading a sketch to a destination board successfully. Testing sketch is using serial, TFT display over SPI.

platformio.used for testing
```
[env:T-Display]
platform = https://github.com/platformio/platform-espressif32.git
board = lilygo_t-display
framework = arduino
monitor_speed = 115200
build_flags = -D ARDUINO_LILYGO_T_DISPLAY_S3
platform_packages =
    framework-arduinoespressif32 @ https://github.com/PBrunot/arduino-esp32#feature-lilygo-tdisplay
lib_deps = 
	moononournation/GFX Library for Arduino@^1.3.7
	Wire
	SPI
```

## Related links

This is required to add support in platformio for the same board, as per platformio esp32 policies : https://github.com/platformio/platform-espressif32/issues/209

2023-08-15 12:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8533) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8533) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=8533) it.</sub>

2023-08-23 10:56 UTC, P-R-O-C-H-Y requested changes
@PBrunot Please take a look on my comments. After its fixed the board addition can be merged :)

2023-08-23 10:56 UTC, P-R-O-C-H-Y commented on boards.txt
> +lilygo_t_display.menu.FlashSize.2M.build.partitions=minimal
As the boards will be 4MB or 16MB, this part can be removed and users will not be able to select wrong flash size.

2023-08-23 10:56 UTC, P-R-O-C-H-Y commented on boards.txt
> +
Please add EraseFlash at the end of board definition. Else this board will not work in Arduino IDE.
```
lilygo_t_display.menu.EraseFlash.none=Disabled
lilygo_t_display.menu.EraseFlash.none.upload.erase_cmd=
lilygo_t_display.menu.EraseFlash.all=Enabled
lilygo_t_display.menu.EraseFlash.all.upload.erase_cmd=-e
```

2023-08-26 09:04 UTC, PBrunot commented
Thanks, I've implemented your comments.

2023-08-29 10:51 UTC, merged

2023-09-01 01:40 UTC, SuGlider commented
Attention::: WRONG FILE NAME ---> [pins_arduino.h.txt](https://github.com/espressif/arduino-esp32/pull/8533/files#diff-ec7cb232a3c534c4ec6f10b4d5143ad9d6c87760985f277d46370ad3d5aa0211)

I'll fix it in the GPIO48 PR.

2023-09-01 07:47 UTC, PBrunot commented
Sorry about that & thank you for your fix.