Added support for Aventen S3 Sync
espressif/arduino-esp32 pull request #8570
Opened 2023-08-27 09:18 UTC by avencan

## Description of Change
Introduced the Aventen-S3-Sync, an custom ESP32-S3 based board.

## Tests scenarios
The addition of the board has been tested with various different code and libraries, and we have ensured it will definitely work.

2023-08-27 09:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8570) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8570) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=8570) it.</sub>

2023-08-28 11:40 UTC, P-R-O-C-H-Y requested changes
@avencan Please take a look on my comments.

2023-08-28 11:40 UTC, P-R-O-C-H-Y commented on boards.txt
> +aventen_s3_sync.build.variant=esp32s3
You are not using your variants pins_arduino.h file. Please change this.
```suggestion
aventen_s3_sync.build.variant=Aventen_S3_Sync
```

2023-08-28 11:40 UTC, P-R-O-C-H-Y commented on boards.txt
> +aventen_s3_sync.build.flash_size=4MB
Idk what flash size you have on board. But here you have default 4MB, but later in config you have only 16 MB option.
So from that I assume this should be changed to 16MB if I am correct.
```suggestion
aventen_s3_sync.build.flash_size=16MB
```

2023-08-28 11:40 UTC, P-R-O-C-H-Y commented on boards.txt
> +
Remove unnecessary line
```suggestion
```

2023-08-28 11:40 UTC, P-R-O-C-H-Y commented on boards.txt
> +esp32doit-devkit-v1.name=DOIT ESP32 V1
Please revert this as this should not be part of the PR.

2023-08-28 11:40 UTC, P-R-O-C-H-Y commented on boards.txt
> +##############################################################
This should not be there. Not part of this PR.

2023-08-28 15:58 UTC, avencan commented
Hi @P-R-O-C-H-Y 

I have made the changes as requested, aswell as removing some unnecessary things, I hope everything is fine with it now :).

Here's some details about the board - if needed for errors.

![image](https://github.com/espressif/arduino-esp32/assets/140997610/485119aa-d08c-49ea-a110-b9dbd6619e4c)
![image](https://github.com/espressif/arduino-esp32/assets/140997610/fa4c9866-9e11-44ed-ad83-dacb13cf6161)

Thanks

2023-08-29 10:09 UTC, P-R-O-C-H-Y commented
Hi @avencan,

the new commit with changes to boards.txt file is messed up: `24,329 additions, 24,382 deletions` so I cannot easily check the changes. Can you try to revert this commit and push the changes again? Thanks

2023-08-29 14:28 UTC, avencan commented
Hi @P-R-O-C-H-Y 

I don't think I can revert it, and I don't really know why this happened, would you be able to check the changes on a local git client? Sorry about this

Thank you

2023-08-29 14:50 UTC, P-R-O-C-H-Y commented
Hi @avencan, i will try if that will do good, but first can you please resolve conflicts please? Thanks

2023-08-29 16:46 UTC, closed without merging