Added support for the Aventen S3 Sync
espressif/arduino-esp32 pull request #8587
Opened 2023-08-30 16:18 UTC by avencan

## Description of Change
Addition of Aventen S3 Sync

## Tests scenarios
NA

2023-08-30 16:19 UTC, avencan commented
@P-R-O-C-H-Y  I hope it all works now :)? 

Also, I have a question, I have tested it and it seems it has an longer upload time than other board variants?

Thanks

2023-08-30 16:41 UTC, P-R-O-C-H-Y approved these changes
Looks good now :) LGTM

2023-08-30 16:42 UTC, P-R-O-C-H-Y commented
> @P-R-O-C-H-Y I hope it all works now :)?
> 
> Also, I have a question, I have tested it and it seems it has an longer upload time than other board variants?
> 
> Thanks

I guess it have to be related to the flash size. I don't see any reason to take longer time than in other variants.

2023-08-30 17:25 UTC, lucasssvaz requested changes

2023-08-30 17:25 UTC, lucasssvaz commented on variants/Aventen_S3_Sync/pins_arduino.h
> +#define digitalPinHasPWM(p)         (p < 46)
This will create problems when using pin 48 for interrupts. Take a look at #8562 for the recommended changes.

2023-08-31 03:13 UTC, avencan commented
@lucasssvaz I hope the new commit fixes that

2023-08-31 10:35 UTC, merged