Add support for custom panic handler
espressif/arduino-esp32 pull request #8711
Opened 2023-10-05 12:15 UTC by me-no-dev

redo for: https://github.com/espressif/arduino-esp32/pull/8574

2023-10-05 14:16 UTC, lucasssvaz requested changes
Change `get_arduino_panic_handler` to avoid compilation warning. `arduino_panic_handler_t` is already a pointer

2023-10-05 14:16 UTC, lucasssvaz commented on cores/esp32/esp32-hal-misc.c
> +}
```suggestion
arduino_panic_handler_t get_arduino_panic_handler(void){
    return _panic_handler;
}
```

2023-10-05 14:16 UTC, lucasssvaz commented on cores/esp32/esp32-hal.h
> +arduino_panic_handler_t * get_arduino_panic_handler(void);
```suggestion
arduino_panic_handler_t get_arduino_panic_handler(void);
```

2023-10-05 16:17 UTC, lucasssvaz approved these changes

2023-10-06 10:48 UTC, merged

2024-10-21 23:42 UTC, Laxilef commented
Hi @me-no-dev 

Please explain how to work with the ``set_arduino_panic_handler``? Previously, I created an array of pairs and filled it like this:
```c++
std::make_pair(esp_cpu_process_stack_pc(stk_frame.pc), stk_frame.sp);
```
But now the backtrace array in the ``arduino_panic_info_t`` structure is filled only PC:
```c++
    pc_ptr = esp_cpu_process_stack_pc(stk_frame.pc);
    if (esp_ptr_executable((void *)pc_ptr)) {
      p_info.backtrace[p_info.backtrace_len++] = pc_ptr;
    // ...
```

How can I get SP? Thanks.