Create new pins_arduino.h and update boards.txt to add Heltec Wireless Tracker board
espressif/arduino-esp32 pull request #8725
Opened 2023-10-05 19:04 UTC by jhiggason

-----------
## Description of Change
Add Heltec Wireless Tracker to variants and boards.txt using https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/releases as a source.  

This is my first time doing this- not sure if I need to include the libraries they have or not.  (GNSS and LORA are the two that come to mind) 

## Tests scenarios
Please describe on what Hardware and Software combinations you have tested this Pull Request and how.

I'm not 100% sure how to test this but happy to do it since I have a board.  

## Related links
https://github.com/espressif/arduino-esp32/pull/8464
https://github.com/platformio/platform-espressif32/issues/1148

2023-10-05 19:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8725) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8725) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=8725) it.</sub>

2023-10-06 10:23 UTC, P-R-O-C-H-Y requested changes
Hi @jhiggason, please take a look on my comment.
Added suggestions for easier fixing.

2023-10-06 10:23 UTC, P-R-O-C-H-Y commented on boards.txt
> +
Please add missing EraseFlash menu.
```suggestion
heltec_wireless_tracker.menu.EraseFlash.none=Disabled
heltec_wireless_tracker.menu.EraseFlash.none.upload.erase_cmd=
heltec_wireless_tracker.menu.EraseFlash.all=Enabled
heltec_wireless_tracker.menu.EraseFlash.all.upload.erase_cmd=-e

```

2023-10-06 10:23 UTC, P-R-O-C-H-Y commented on variants/heltec_wireless_tracker/pins_arduino.h
> +#define NUM_ANALOG_INPUTS       20
This is no longer needed and defined globally for all SOCs in Arduino.h file.
```suggestion
```

2023-10-06 10:23 UTC, P-R-O-C-H-Y commented on variants/heltec_wireless_tracker/pins_arduino.h
> +#define digitalPinHasPWM(p)         (p < 46)
This is no longer needed and defined globally for all SOCs in Arduino.h file.
```suggestion
```

2023-10-11 19:26 UTC, jhiggason commented
@P-R-O-C-H-Y  I made the requested changes- can you check them out for me?  Do you see anything else wrong with it?

2023-10-12 07:24 UTC, P-R-O-C-H-Y commented
@jhiggason Hi, you did not followed up the suggestion or required change for the erase flash menu. Can you fix that and place it on correct place of the board definition (the end, like all other boards have it)?

2023-10-12 07:43 UTC, P-R-O-C-H-Y requested changes
@jhiggason PTAL

2023-10-12 07:43 UTC, P-R-O-C-H-Y commented on boards.txt
> +heltec_wireless_tracker.menu.EraseFlash.none=Disabled
build.board.defines already exist at the end of board definition.
Erase flash menu is not complete and please add it to the end of board definition as other boards do (check next comment)
```suggestion

```

2023-10-12 07:43 UTC, P-R-O-C-H-Y commented on boards.txt
> +
```suggestion
heltec_wireless_tracker.menu.EraseFlash.none=Disabled
heltec_wireless_tracker.menu.EraseFlash.none.upload.erase_cmd=
heltec_wireless_tracker.menu.EraseFlash.all=Enabled
heltec_wireless_tracker.menu.EraseFlash.all.upload.erase_cmd=-e

```

2023-10-13 17:50 UTC, jhiggason commented on boards.txt
> +
Added this section.

2023-10-13 17:51 UTC, jhiggason commented
@P-R-O-C-H-Y Ok let's try again.  Is there a way for me to build this and test it before we merge it into master?  Could you point me to a doc if yes?  (Sorry, I'm just starting my programming journey with ESP32's and some of this, like source building and library control is new to me)  Thank you for your help with this- I really do appreciate it.

2023-10-17 06:34 UTC, P-R-O-C-H-Y requested changes

2023-10-17 06:34 UTC, P-R-O-C-H-Y commented on boards.txt
> +heltec_wireless_tracker.menu.EraseFlash.none=Disabled
Please remove this line as it was added to the end of the file.
```suggestion
```

2023-10-17 06:34 UTC, P-R-O-C-H-Y commented on boards.txt
> +heltec_wireless_tracker.build.extra_libs=-lheltec_{build.cdc_on_boot}
Can you please come this part to the end of the board definition just right above EraseFlash menu?

2023-10-17 06:43 UTC, P-R-O-C-H-Y commented
> @P-R-O-C-H-Y Ok let's try again. Is there a way for me to build this and test it before we merge it into master? Could you point me to a doc if yes? (Sorry, I'm just starting my programming journey with ESP32's and some of this, like source building and library control is new to me) Thank you for your help with this- I really do appreciate it.

@jhiggason Yes you can build na test the board configuration. You can just add the changes you are adding to the ESP32 core. 
If you install ESP32 Arduino Core through Boards manager in Arduino IDE, you can find the location of esp32 by going to Arduino15 folder located here:
```
   Windows: C:\Users\{username}\AppData\Local\Arduino15
   macOS: /Users/{username}/Library/Arduino15
   Linux: home/{username}/.arduino15
```
and than go to `/packages/esp32/hardware/esp32/<version>/...` and there is the boards.txt file and variants folder you are editing :).

If you Installed manually from GitHub, it is located in `Documents/Arduino/hardware/`.
After you add the changes there, you may need to restart the Arduino IDE to see the new board you added (better to use old IDE 1.8.x).

2023-11-28 12:11 UTC, VojtechBartoska commented
any updates on this @jhiggason?

2023-11-28 18:08 UTC, jhiggason commented
Sorry!  Completely forgot about this-  I'll try to test and get back to you today.

2023-12-19 22:31 UTC, Lapporatory992 commented
Hi,
Would it possible to add the HeltecESP32 "wireless_paper" board to the list of Espressif supported boards ?
https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/blob/master/esp32/boards.txt

Thank you,

2024-01-13 11:42 UTC, songpola commented
@jhiggason Hello! Just to let you know that they just released 1.0.0 release. :D

2024-01-23 12:10 UTC, merged