Added example to demonstrate using HardwareSerial with RS485 interfaces
espressif/arduino-esp32 pull request #8941
Opened 2023-11-29 18:00 UTC by econeale

## Description of Change
This PR adds an example to the set of Serial examples that demonstrates how to use the HardwareSerial interface to communicate using RS485 hardware. The demo simply echos data received on one interface to the other. 

## Tests scenarios
I have tested with Adafruit Huzzah32 (ESP32) and Adafruit QT Py ESP32-S3 using a MAX33046E translation chip. 

## Related links
Addendum to #8934 
Potentially related to #8755

2023-11-29 18:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8941) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=8941) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=8941) it.</sub>

2023-12-01 13:11 UTC, lucasssvaz requested changes

2023-12-01 13:11 UTC, lucasssvaz commented on libraries/ESP32/examples/Serial/RS485_Echo_Demo/RS485_Echo_Demo.ino
> +  if(!RS485.setPins(-1, -1, -1, RS485_RTS_PIN)){
```suggestion
  RS485.begin(9600, SERIAL_8N1, RS485_RX_PIN, RS485_TX_PIN);
  while(!RS485) { delay(10); }
  if(!RS485.setPins(-1, -1, -1, RS485_RTS_PIN)){
```

2023-12-01 14:53 UTC, lucasssvaz approved these changes

2023-12-01 14:54 UTC, lucasssvaz commented on libraries/ESP32/examples/Serial/RS485_Echo_Demo/RS485_Echo_Demo.ino
> +#include <HardwareSerial.h>
```suggestion
```

2023-12-01 19:04 UTC, atanisoft commented on libraries/ESP32/examples/Serial/RS485_Echo_Demo/RS485_Echo_Demo.ino
> +#define RS485_RTS_PIN 37
pin 37 doesn't exist on all ESP32 variants, I'd suggest moving this to GPIO 4 or other IO pin that is generally available.

2023-12-12 07:34 UTC, VojtechBartoska commented
Hi @econeale, can you please update your PR up to the reviews? Thanks a lot!

2023-12-12 14:07 UTC, lucasssvaz approved these changes

2023-12-20 14:05 UTC, SuGlider commented
@me-no-dev - this PR can also be merged.

2023-12-20 14:35 UTC, merged