Add Board support for Geekble ESP32-C3 Custom Module
espressif/arduino-esp32 pull request #9260
Opened 2024-02-16 15:15 UTC by SooDragon

## Description of Change

Add board support for Geekble ESP32C3 Module

## Tests scenarios

I have tested with Arduino IDE, Version 2.3.1 and 1.8.19. Verified by compiling, uploading, testing using IO Examples and Bluetooth examples.

## Related links

- https://cafe.naver.com/geekbleofficial/14074
- https://www.youtube.com/@geekble
- https://github.com/Geekble-Maker/Geekble_LieDetector

2024-02-16 18:08 UTC, P-R-O-C-H-Y requested changes
@SooDragon Small fix needed, but overall looks good :)

2024-02-16 18:08 UTC, P-R-O-C-H-Y commented on variants/Geekble_ESP32C3/pins_arduino.h
> +#define digitalPinHasPWM(p)         (p < EXTERNAL_NUM_INTERRUPTS)
Please remove this part as it is now defined globally per SoC.

2024-02-17 10:10 UTC, P-R-O-C-H-Y approved these changes

2024-02-21 14:17 UTC, me-no-dev commented
@SooDragon please fix the conflict :) it happens when more than one PR exists for a new board.

2024-02-23 16:24 UTC, SooDragon commented
@P-R-O-C-H-Y Thank you for ping :)

2024-02-23 17:04 UTC, merged