Heltec ESP32 Series boards update
espressif/arduino-esp32 pull request #9367
Opened 2024-03-13 09:35 UTC by Heltec-Aaron-Lee

## Description of Change

Fixes:

- Fixes some basic information about previous development boards;
- Fixes the option for LoRaWAN parameter in the Tools menu;
- Remove useless parameter options;
- Correcting typing issues.

Add:
- Add Heltec new boards to the development framework;
- Add external 32K Crystal oscillator option for LoRawWAN.

2024-03-13 09:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=9367) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=9367) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=9367) it.</sub>

2024-03-14 12:55 UTC, P-R-O-C-H-Y requested changes
@Heltec-Aaron-Lee PTAL on my comments.
Few point to be changed in almost all boards definition ( I did not cover everything in the review):
- all build.board names must be uppercase
- check formatting to make everything clear, remove or add empty lines please.

When fixed, ping me to review again.

2024-03-14 12:55 UTC, P-R-O-C-H-Y commented on variants/heltec_capsule_sensor_v3/pins_arduino.h
> +#define NUM_ANALOG_INPUTS       20
This is no longer required, as it's defined globally per SoC. 
```suggestion
```

2024-03-14 12:55 UTC, P-R-O-C-H-Y commented on variants/heltec_capsule_sensor_v3/pins_arduino.h
> +#define digitalPinHasPWM(p)         (p < 46)
This is no longer required, as its defined globally per SoC.
```suggestion
```

2024-03-14 12:55 UTC, P-R-O-C-H-Y commented on variants/heltec_ht_de01/pins_arduino.h
> +#define digitalPinHasPWM(p)         (p < 34)
Same here, this is no longer required, as its defined globally per SoC.
```suggestion
```

2024-03-14 12:55 UTC, P-R-O-C-H-Y commented on variants/heltec_wireless_mini_shell/pins_arduino.h
> +#define NUM_ANALOG_INPUTS       6
Same here, this is no longer required, as its defined globally per SoC.
```suggestion
```

2024-03-14 12:55 UTC, P-R-O-C-H-Y commented on variants/heltec_wireless_mini_shell/pins_arduino.h
> +#define digitalPinHasPWM(p)         (p < EXTERNAL_NUM_INTERRUPTS)
Same here, this is no longer required, as its defined globally per SoC.
```suggestion
```

2024-03-14 12:55 UTC, P-R-O-C-H-Y commented on boards.txt
> +heltec_wifi_kit_32.build.board=heltec_wifi_kit_32
The build.board has to be uppercase, please revert this change in all boards.

2024-03-14 12:55 UTC, P-R-O-C-H-Y commented on boards.txt
> +heltec_wireless_stick_V3.menu.EraseFlash.all.upload.erase_cmd=-e
Please add an empty line before board ending (####)

2024-03-14 12:55 UTC, P-R-O-C-H-Y commented on boards.txt
> +heltec_wireless_shell_V3.menu.EraseFlash.all.upload.erase_cmd=-e
Please add an empty line before board definition ending (####)

2024-03-14 12:55 UTC, P-R-O-C-H-Y commented on boards.txt
> +heltec_capsule_sensor_V3.build.board=heltec_capsule_sensor_V3
build.board needs to be uppercase

2024-03-14 12:55 UTC, P-R-O-C-H-Y commented on boards.txt
> +
Remove 2 unnecessary empty lines.
```suggestion
```

2024-03-15 10:08 UTC, Heltec-Aaron-Lee commented
@P-R-O-C-H-Y 
Hi, thank you very much for taking the time to review. I have corrected the issues you mentioned, please review again.

2024-03-15 12:04 UTC, P-R-O-C-H-Y requested changes
Looks good, just one fix needed :)
PTAL @Heltec-Aaron-Lee

2024-03-15 12:04 UTC, P-R-O-C-H-Y commented on boards.txt
The Heltec E-Ink driver is missing the Eraseflash menu. Please add it.
```suggestion

heltec_ht_de01.menu.EraseFlash.none=Disabled
heltec_ht_de01.menu.EraseFlash.none.upload.erase_cmd=
heltec_ht_de01.menu.EraseFlash.all=Enabled
heltec_ht_de01.menu.EraseFlash.all.upload.erase_cmd=-e
```

2024-03-16 03:18 UTC, Heltec-Aaron-Lee commented
I apologize for my carelessness... I have corrected this issue, please review it again
@P-R-O-C-H-Y

2024-03-18 10:32 UTC, P-R-O-C-H-Y approved these changes

2024-03-18 12:32 UTC, merged