Adds LilyGo T Relay S3 board definition
espressif/arduino-esp32 pull request #9449
Opened 2024-04-02 22:06 UTC by LordRafa

*By completing this PR sufficiently, you help us to review this Pull Request quicker and also help improve the quality of Release Notes*

## Description of Change
Add  [LilyGo T Relay S3](https://github.com/Xinyuan-LilyGO/LilyGo-T-Relay/blob/main/docs/RELAY_ESP32S3.MD) board definition

## Tests scenarios
Tested compilation against basic examples.

## Related links

Pins documentation is wrong. I check pins avaiale directly on the [schematic](https://github.com/Xinyuan-LilyGO/LilyGo-T-Relay/blob/main/Schematic/T_Relay6_ESP32S3.pdf)

2024-04-02 22:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=9449) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=9449) before we can accept your contribution.<br/><hr/>**Rafael Waldo Delgado Doblas** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=9449) it.</sub>

2024-04-03 07:40 UTC, P-R-O-C-H-Y commented
@LordRafa can you please sign CLA?

2024-04-03 07:49 UTC, P-R-O-C-H-Y requested changes
@LordRafa PTAL

2024-04-03 07:49 UTC, P-R-O-C-H-Y commented on variants/lilygo_t_relay_s3/pins_arduino.h
> +#define digitalPinHasPWM(p)         (p < 46)
This part have been moved and its defined globally per SoC. Please remove it.
```suggestion
```

2024-04-04 15:26 UTC, lucasssvaz requested changes
Please also recommit your changes using only your Github username otherwise the CLA won't be able to be properly signed

2024-04-17 20:08 UTC, me-no-dev commented
Closing for lack of response. We can not merge PRs without signed CLA. @LordRafa feel free to open a new PR if you are willing to sign the CLA

2024-04-17 20:08 UTC, closed without merging