docs(lib-builder): Add docker image documentation
espressif/arduino-esp32 pull request #9621
Opened 2024-05-13 15:52 UTC by lucasssvaz

## Description of Change
Add documentation for the Lib Builder Docker Image.

2024-05-13 16:10 UTC, me-no-dev commented on docs/en/lib_builder.rst
> +* esp32h2
esp32c6?

2024-05-13 20:04 UTC, lucasssvaz commented
@P-R-O-C-H-Y PTAL at why Wokwi tests are failing.

2024-05-13 21:12 UTC, me-no-dev approved these changes

2024-05-14 06:08 UTC, P-R-O-C-H-Y requested changes
Small nitpicks

2024-05-14 06:08 UTC, P-R-O-C-H-Y commented on docs/en/lib_builder.rst
> +   When the mounted directory, ``/arduino-esp32``, contains a git repository owned by a different user (``UID``) than the one running the Docker container,
```suggestion
   When the mounted directory ``/arduino-esp32`` contains a git repository owned by a different user (``UID``) than the one running the Docker container,
```

2024-05-14 06:08 UTC, P-R-O-C-H-Y commented on docs/en/lib_builder.rst
> +After running the above command, you will be inside the container and can build the libraries using the user interface.
```suggestion
After running the above command, you will be inside the container and the libraries can be built using the user interface.
```

2024-05-14 09:46 UTC, P-R-O-C-H-Y approved these changes

2024-05-14 10:46 UTC, merged