feat(3rd party board): Adding ViraLink IoT Gate Boards
espressif/arduino-esp32 pull request #9841
Opened 2024-06-12 15:14 UTC by armp30

### Description of Change
feat(3rd party board): Adding ViraLink IoT Gate Boards

### Tests scenarios
I have tested my Pull Request on Arduino-esp32 core v3.0.1.

2024-06-13 21:11 UTC, P-R-O-C-H-Y requested changes
As @me-no-dev commented, please change the `build.board` to uppercase.

2024-06-20 11:15 UTC, me-no-dev commented
@armp30 no response for over a week? Would you please finish this? If no further response, we will close it.

2024-06-22 15:35 UTC, armp30 commented
@me-no-dev fixed

2024-06-24 07:35 UTC, P-R-O-C-H-Y requested changes
@armp30 Please fix the missing default SPI pins.

2024-06-24 07:35 UTC, P-R-O-C-H-Y commented on variants/ViraLink-G0.1/pins_arduino.h
> +
Please provide default SPI pins. If you don't want to specify them, you can use -1 as shown in suggestion.
```suggestion
static const uint8_t SS = -1;
static const uint8_t MOSI = -1;
static const uint8_t SCK = -1;
static const uint8_t MISO = -1;
```

2024-06-24 07:35 UTC, P-R-O-C-H-Y commented on variants/ViraLink-G1.1/pins_arduino.h
> +static const uint8_t SCL = 16;
Please provide default SPI pins. If you don't want to specify them, you can use -1 as shown in suggestion.
```suggestion
static const uint8_t SS = -1;
static const uint8_t MOSI = -1;
static const uint8_t SCK = -1;
static const uint8_t MISO = -1;
```

2024-06-25 09:25 UTC, P-R-O-C-H-Y approved these changes
LGTM.

2024-06-25 13:31 UTC, merged