add new adafruit feather c6 rev B :)
espressif/arduino-esp32 pull request #9961
Opened 2024-06-29 16:46 UTC by ladyada

tested with hardware!

![image](https://github.com/espressif/arduino-esp32/assets/1214161/f7e842a6-4f43-4a08-ad62-963130cade6c)

2024-06-29 18:45 UTC, ladyada commented
feat: add feather esp32-c6 new hardware

2024-07-01 08:42 UTC, P-R-O-C-H-Y requested changes
@ladyada Looking good, just small fix needed on Zigbee.

2024-07-01 08:42 UTC, P-R-O-C-H-Y commented on boards.txt
> +adafruit_feather_esp32c6.menu.ZigbeeMode.ed.build.zigbee_libs=-lesp_zb_api_ed -lesp_zb_cli_command -lzboss_stack.ed.trace -lzboss_stack.ed -lzboss_port
Please remove the -lzboss_stack.ed.trace from linker, as it's no longer available.
```suggestion
adafruit_feather_esp32c6.menu.ZigbeeMode.ed.build.zigbee_libs=-lesp_zb_api_ed -lesp_zb_cli_command -lzboss_stack.ed -lzboss_port
```

2024-07-01 08:42 UTC, P-R-O-C-H-Y commented on boards.txt
> +adafruit_feather_esp32c6.menu.ZigbeeMode.zczr.build.zigbee_libs=-lesp_zb_api_zczr -lesp_zb_cli_command -lzboss_stack.zczr.trace -lzboss_stack.zczr -lzboss_port
Please remove the -lzboss_stack.zczr.trace from linker, as it's no longer available.
```suggestion
adafruit_feather_esp32c6.menu.ZigbeeMode.zczr.build.zigbee_libs=-lesp_zb_api_zczr -lesp_zb_cli_command -lzboss_stack.zczr -lzboss_port
```

2024-07-01 16:50 UTC, me-no-dev commented
@P-R-O-C-H-Y PTAL

2024-07-01 17:31 UTC, P-R-O-C-H-Y approved these changes

2024-07-01 21:48 UTC, me-no-dev commented
@hathach please apply the changes requested by the pre-commit hook: https://github.com/espressif/arduino-esp32/actions/runs/9748594236/job/26903898166?pr=9961#step:8:28

They could not be automatically applied to PRs from organizations. Thanks!

2024-07-02 07:08 UTC, hathach commented
@me-no-dev thanks for reminder, I have fixed the pre-commit clang format

2024-07-02 07:32 UTC, merged